version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirement.txt -t lib
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase
  build:
    commands:
      - echo " new Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post-build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://doordash-lambda-zip-cb/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name doordash-lambda-cicd --s3-bucket doordash-lambda-zip-cb --s3-key deployment_package.zip
      - echo "Deployment complete!"

